[theme]
base = "dark"
primaryColor = "#00796b" 
backgroundColor = "#121212" 
secondaryBackgroundColor = "#313131"
textColor = "#f5f5f5" 
font = "monospace"  # Optional: "serif" or "sans-serif"


[server]
headless = true
enableCORS = false
port = 8080

[caching]
maxEntries = 500
ttl = 7200  # Keep cache valid for 2 hours

[server.fileWatcher]
watcherType = "poll"

[layout]
wideMode = true